import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { Formik, Field, Form } from 'formik';
import { GoogleMap, LoadScript, Marker } from '@react-google-maps/api';



const Page = () => {

    const router = useRouter();

    const [locations, setLocations] = useState([]);

    useEffect(() => {
        (async () => {
            navigator.geolocation.getCurrentPosition(position => {
                setLocations({
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                });
            }, (err) => {
                console.log(err.message);
            });
        })();
    }, [])

    const { lat, lng } = locations;


    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <section>
                <h1 style={{ textAlign: "center" }}>Ver Postos Disponiveis `${process.env.GOOGLE_MAPS_API_KEY}`</h1>
                <Formik
                    initialValues={{
                        lat: 0,
                        lng: 0
                    }}
                    onSubmit={(lat, lng) => {
                        navigator.geolocation.getCurrentPosition(position => {

                            lat = position.coords.latitude;
                            lng = position.coords.longitude;

                            router.push(`/places?lat=${lat}&lng=${lng}`);
                        });
                    }}
                >
                    <Form>
                        <button type="submit"
                            className="custom-map-control-button"
                            style={{
                                marginLeft: "auto", marginRight: 'auto'
                            }}>Pequisar Hoteis</button>
                    </Form>
                </Formik>
            </section>

            {/* Sim eu sei que deixar o chave de api não é uma boa pratica, 
mas está chave já foi configurada no google e 
somente está aplicação tem acesso*/}
            <LoadScript
                googleMapsApiKey={process.env.GOOGLE_MAPS_API_KEY}>
                <GoogleMap
                    mapContainerStyle={{ height: "70vh", width: "100%" }}
                    zoom={14}
                    center={{ lat: Number(lat), lng: Number(lng) }}>

                    <Marker key={lat + 1} position={{ lat: Number(lat), lng: Number(lng) }} />
                </GoogleMap>
            </LoadScript>

        </div>
    )

}


export default Page;
