import Head from 'next/head';
import axios from 'axios';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { GoogleMap, LoadScript, Marker } from '@react-google-maps/api';


// Next.js API route support: https://nextjs.org/docs/api-routes/introduction


const SearchHotelsGoogleApi = () => {

    const router = useRouter();
    const { lat, lng } = router.query;

    const [locations, setLocations] = useState([]);

    useEffect(() => {

        async function fetchData() {
            try {
                const res = await axios.get(`http://localhost:3000/api/hello?location=${lat},${lng}`);
                setLocations(res.data);
            } catch (err) {
                console.log(err);
            }
        }
        fetchData();
    }, [lat, lng]);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* Sim eu sei que deixar o chave de api não é uma boa pratica, 
mas está chave já foi configurada no google e 
somente está aplicação tem acesso*/}
            <LoadScript
                googleMapsApiKey='AIzaSyBXjOchbRJ8GO8RYOUyCnNDPxclQbFzPv4'>
                <GoogleMap
                    mapContainerStyle={{ height: "100vh", width: "100%" }}
                    zoom={14}
                    center={{ lat: Number(lat), lng: Number(lng) }}>
                    {
                        locations.map((item, keys) => {
                            return (
                                <Marker key={keys} position={item.location} />
                            )
                        })
                    }
                </GoogleMap>
            </LoadScript>

        </div>
    )
}

export default SearchHotelsGoogleApi;